// Generated by CoffeeScript 1.10.0
import { test, moduleFor } from 'ember-qunit';
moduleFor('controller:entity', {
  integration: true
});

test('it exists', function(assert) {
  var controller;
  controller = this.subject();
  return assert.ok(controller);
});
