// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var EditableLabelComponent;

EditableLabelComponent = Ember.Component.extend({
  isEditing: false,
  actions: {
    toggleEditable: function() {
      if (this.get('isEditing')) {
        return this.set('isEditing', false);
      } else {
        return this.set('isEditing', true);
      }
    }
  }
});

export default EditableLabelComponent;
