// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var UserSearchComponent;

UserSearchComponent = Ember.Component.extend({
  searchQueryChanged: (function() {
    this.set('hasSearched', true);
    return this.runQuery();
  }).observes("searchQuery.length"),
  runQuery: function() {
    return this.sendAction('getUsers', this.get('searchQuery'));
  },
  actions: {
    toggleUser: function() {
      return this.sendAction('toggleUser');
    }
  }
});

export default UserSearchComponent;
