// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
var EmailFiltersTransform;

EmailFiltersTransform = DS.Transform.extend({
  deserialize: function(serialized) {
    return JSON.parse(serialized);
  },
  serialize: function(deserialized) {
    return JSON.stringify(deserialized);
  }
});

export default EmailFiltersTransform;
