// Generated by CoffeeScript 1.10.0
import { test, moduleFor } from 'ember-qunit';
moduleFor('route:campaigns/index', {
  integration: true

});

test('it exists', function(assert) {
  var route;
  route = this.subject();
  return assert.ok(route);
});
