import { Factory, faker} from 'ember-cli-mirage';

export default Factory.extend({
  name(i) {
    return `campaign ${i}`;
  },
  slug(i) {return `campaign-${i}`;},
  quote: faker.company.bs,
  description: faker.company.catchPhrase,
  whyDonations: faker.company.catchPhrase,
  personMsg: faker.company.catchPhrase,
  howDonationsUsed: faker.company.catchPhrase,
  emailLogoHead: faker.image.avatar,
  emailLogoBody: faker.image.avatar,
  replyTo: faker.internet.email,
  startDate: faker.date.past,
  endDate: faker.date.future,
  goal: faker.random.number,
  totalRaised: faker.random.number,
  memberGoal: faker.random.number,
  totalDonors: faker.random.number,
  totalGifts: faker.random.number,
  teamSize: faker.random.number,
  canUpdateCampaign: faker.random.boolean,
  totalDelivered: faker.random.number,
  totalEmail_sent: faker.random.number,
  totalEmail_sent_by_day: {},
  totalOpens: faker.random.number,
  totalOpensByDay: {},
  totalClicks: faker.random.number,
  totalClicksByDay: {},
  totalWsShare: faker.random.number,
  totalWsShareByDay: {},
  totalWsCarousel: faker.random.number,
  totalWsCarouselByDay: {},
  totalWsFacebook: faker.random.number,
  totalWsFacebookByDay: {},
  totalWsEmail: faker.random.number,
  totalWsEmailByDay: {},
  totalWsTwitter: faker.random.number,
  totalWsTwitterByDay: {},
  totalWsSms: faker.random.number,
  totalWsSmsByDay: {},
  totalWsContribute: faker.random.number,
  totalWsContributeByDay: {},
  totalWsDonate: faker.random.number,
  totalWsDonateByDay: {},
  totalWebStats: faker.random.number,
});
