// Generated by CoffeeScript 1.10.0
import { moduleFor, test } from 'ember-qunit';
moduleFor('adapter:donation', 'Unit | Adapter | DonationAdapter', {
  needs: ['service:session', 'service:settings', 'service:notify']
});

test('it exists', function(assert) {
  var adapter;
  adapter = this.subject();
  return assert.ok(adapter);
});
