// Generated by CoffeeScript 1.10.0
import { test, moduleFor } from 'ember-qunit';
moduleFor('serializer:user', {});

test('it exists', function(assert) {
  var serializer;
  serializer = this.subject();
  return assert.ok(serializer);
});
