// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
var CampaignImage;

CampaignImage = DS.Model.extend({
  campaign: DS.belongsTo('campaign', { async: false }),
  name: DS.attr('string'),
  position: DS.attr('number'),
  alt_text: DS.attr('string')
});

export default CampaignImage;
