// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
var Contact;

Contact = DS.Model.extend({
  first_name:     DS.attr('string'),
  last_name:      DS.attr('string'),
  email:          DS.attr('string'),
  type:           DS.attr('string'),
  facebook_id:    DS.attr('string'),
  img:            DS.attr('string'),
  current_user:   DS.belongsTo('current_user', {
    async: true
  }),
  campaign:       DS.belongsTo('campaign', {
    async: true
  }),
  invitations:    DS.hasMany('invitation', {
    async: true
  }),
  converted:      DS.attr('boolean')
});

export default Contact;
