// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
var Invitation;

Invitation = DS.Model.extend({
  campaign: DS.belongsTo('campaign', {
    async: true
  }),
  contact: DS.belongsTo('contact', {
    async: true
  }),
  status: DS.attr("string"),
  name: DS.attr("string"),
  total_opens: DS.attr("number"),
  total_share_actions: DS.attr("number"),
  total_donate_actions: DS.attr("number"),
  sum_donations: DS.attr("number"),
  invitation_email: DS.attr("string"),
  likely_to_donate: DS.attr("string"),
  total_clicks: DS.attr("string")
});

export default Invitation;
